language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: DkBvSeyTeDOsDy2X+VA/vWO+wEYi4xC+c/lTjH4nsbBloQohx9KpHTQG5F+cBegR2dW9tOzMqAAUGe9fYg6jjx69aFTiNvVkpJcm9SaNjM0qs3BwjnU8EsQo7Pytt1X/l9zWSYS0Uv1dkAQ7qxup3ceKyfnuqGApSU4tRSBdzF7E3UiEY7O6a8Gu6TLQu19dKME7Nb/JXK5meJDXck9ioYeAKamWoga9G1phQVoSqVU/k/mFeGXZg5DvmA3Z4sYEp02huBH1QFofOQYmwE6Uf6xqjyXXzJkuavJF91HhdNee0zUTOsq2h157r5eve9m81wF9bRjC9ukS6rE4HBS7/y7cN/yEI864ufZVq68Khc06kwfqYkhah1gjF6YPkzhaUSxyWGLW4367lBQ/ImL3GfiCILT8Xm+LsA/sqxUFV0rnjKKOV/oJeDVIqkX3o2xJw0Uj4+7uj3kJ6zdKxDNfNFt4e+wc0/cpt45V0A4idVNwxTn8LdGVujebdJBU5WrqhTiDnfHzUjTWEOWaBRjLdtgTnavxy3x+BAbt//NfObohKsF0u8HOxjQ8Skmku+lJaDv5wmsh0gbqFKXDoWMqVgDCnNM8YFdxAhWvzbV1EP6m+nBjfsLJnPykUzE63lhIblQVFZhGqV8DsLyP5Suw3naJt/yK59FqAvIkSGDFUEs=
  app: obscure-brook-80680
  on:
    repo: PeasOfMind/trip-planner-app
